language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: hqQT+S7Gm23NK32iEjahEsKadb6GM9kjMGMAasKG+YXN9O1ArLIIh3guhrANVYRGvNgAj54bjNHoazayHG9mBcybE8msS289bBi7tlymGTv9VgpluQlerPMXiSh0eUg6sDwoM1m8ylJNzf5tt2Gia34RZIoXQCRA9ZCs52cHfydPd7Nee0t4jl5Zwu9O3NgLB1xb7FCxS2SKb5f91/6SulKh9ekuxGBsThqV3IsZ96wtKUpni2+3EPZWySQ54Ar6TwwDsJldDVo1tr6C0kkcmOh/ac1iypWuVGwhLqDDbKj/hOnA35YZyd8em49ms/duOEdFZRwT4LxNRtT6iusM5AHvxvfehfhO2xcWomSv8dIzWZxmIqh9F0PbETCBqs7RDdqYo5k3FMinUk15KYDaGV0Gw8xsITNiN4n3zOO75cpi8sc7by1AWqfUgAJ/E2t5pk3XlFLiqgpQURhcj9RH0ciydhrQ0l8q744aHIITO6xgU6DjXhbxdDu4zJ1O5lfG06tmqt6Abv7WU0Sm05R/iTOkQ8rz8IHMAwky336CFMCmqUMkDWyytbHG1iHaxyZMnGc5MtSFqGDujWyq/TU/+RkP3g7WjvaWZHQWuqFOeD+gto68630clbzRv4jn0JCZCJ8CLcsY8Vie5eCmqT72i0dka8fTvTKErW9YwLx4MdU=
  app: daily-planner-app-api
  on:
    repo: annasheik/daily-planner-api
