language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: PGvBIOfXBmRKqT5/C4bFdg5cP6Qs4fZDU44yxs9JzYlM7r5YF7VJFsm8cjipnPOxUK+QwSRMVNqpcjWrf5HRbkqITFrNhDwNbL8rmkmV6JHeebz5ZzTM0zADorjFuu457F5CBObWTIbvJIbSINjnfgCUJxFb9HP9333iCYag39PyKZyLMvUl4eVX10A08bwA8naR+i8D+cFAEbaCZVbpVK8fZtTciO3RX4XCxV0SUvyWa+MA9HJ53T6BOCzDV4lnp2nq2f2W/wd7i8p0OXoqOqj3yXZeIMF28PhwxAD0pekTt4mxBash+bYe493TmTjwWWZv36Q7OSOBKXCOW0u1SubhB1ItTVnyAPvjeG5IZO6CphnbHguzfi7dVtvj2HNuAV59hpAA7eqCxzKVC7SosvJorGnugh/Nv8ihIWsc4FMeYCtCY4FvlksxRFzgX4rGNct4j8vgSBn2SwdkrKkjgQB/UDbiPE9ZAPUKXj4errLk1yyu31St40mzmFSgYV6edwwde2RziGE2w8R9L5alyu01iwTkFqe9vWj6/e0Ur7uxUeK4kITyd+J0Y4VhNI5g2x0ano83LP1wK81CzV4c4HZRm/4ryC8JLqqbDk5+lXNq7ZBItp1TMxBCXTz5doCbrlMUYzebSPpcv6hEOprHf0VgQ0QDErDH4MBPZnCZ3UY=
  app: daily-planner-app-api
  on:
    repo: annasheik/daily-planner-api
